name = "ArarForecast"
uuid = "5d74c842-a15f-465b-b60b-d92981fc7422"
authors = ["Resul Akay <resul.akay@quantics.io> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
